### ISSUE TITLE
Enable `#` comments

### ISSUE THREAD

**Issue by saxbophone** [pedroburon/dotenv#8]
Should commenting be enabled, by ignoring any lines starting with `#`?
That would be convenient for putting env file explanations within the file.

**Comment by pedroburon** [comment]
Yes, it's a desirable feature. Thx!

**Comment by saxbophone** [comment]
No problem :smile: I'd be happy to work on this in a fork as it should be quite a small fix.

**Comment by pedroburon** [comment]
Perfect! I'll merge your PR asap.

**Comment by saxbophone** [comment]
Thanks, I'll probably do it in a few hours from now.
